version: '3.8'

services:
  back:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - plagicode-network

  db:
    image: postgres:15-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plagicode-network

volumes:
  postgres_data:

networks:
  plagicode-network:
    driver: bridge